### ISSUE TITLE
Support self-hosted gitlab repos

### ISSUE THREAD

**Issue by evilebottnawi** [npm/hosted-git-info#27]
Example: `https://gitlab.my-domain.com/user/repo.git`

**Comment by tatyahoo** [comment]
Bump.

Having the same issue. Using `ember-cli-addon-docs` with `ember deploy production` and it can't parse the corporate github url.

**Comment by silverwind** [comment]
I also discovered the lack of support for generic git hosting in `npm install <url>` which lead me here. `git clone` handles my URLs fine, but `npm` swallows the error from this module and fails with `ENOPACKAGEJSON`.

In my case, it's a gitea instance with URLs like this:

```
git@domain.com:user/repo.git
https://domain.com/user/repo.git
http://domain.com/user/repo.git
```

I think this module could output something like this for it:

````js
{
  type: "generic",
  domain: "domain.com",
  user: "user",
  project: "repo"
}
````

**Comment by silverwind** [comment]
https://github.com/npm/hosted-git-info/pull/30

**Comment by iarna** [comment]
This module is intended to infer URLs on various well known hosted instances, eg, given the repository URL, tell me the URL of the README. This isn't something we can do with private git repos as they don't have any well-known URLs associated with them.

This doesn't impact npm, as npm uses `npm-package-arg` to parse specifiers (the part after the `@`), and that supports generic git URLs.

Adding support for "generic" sites that we can infer nothing from leaves me wondering why you're using this module in the first place? If this module doesn't recognize a repository URL, you should be falling back to generic URL handling _in the consumer_.

**Comment by foodforarabbit** [comment]
I'm using lerna which relies heavily on hosted-git-info to detect git repos. I haven't dug into their code yet, but their symlinking / version updating functionality seems to not work for privately hosted git repos because of this issue specifically.

e.g. 
https://github.com/lerna/lerna/issues/571 
https://github.com/lerna/lerna/issues/1277

I know it isn't really your problem and it should be fixed on their side, but seems like they don't plan to change that any time soon so my only option is to fork it and do it myself. Anyway, just one reason why this would be nice to have :)

**Comment by tatyahoo** [comment]
Hello, 

This employee can no longer access email on this account.  Your email will not be forwarded.

If you have a sales inquiry, please contact sales@yahoo-inc.com

If you require assistance with a legal matter, please contact legal-notices@yahoo-inc.com

Thank you!
